apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cinema
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cinema
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084
